@startuml Basic Sample
!$SYSTEM_BORDER_COLOR ?= "#000000"
!include https://raw.githubUsercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
HIDE_STEREOTYPE()
AddElementTag(SystemDb_colors, $bgColor=SkyBlue, $fontColor=black)

System_Boundary(System_classifier, "Classifier")  {
    System_Boundary(MLFlow, "MLFlow")  {
        SystemDb(ML_Metadata_Repository, "ML_Metadata_Repository", "model performance metrics", $tags="SystemDb_colors") 
    }
}


SHOW_FLOATING_LEGEND()

@enduml