@startuml Basic Sample
!$SYSTEM_BORDER_COLOR ?= "#000000"
!include https://raw.githubUsercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!include System_classification_docs__Model_Repo.puml
!include System_classification_docs__Log_repo.puml


SystemDb_Ext(Data_Source_Production, "Data_Source_Production", "selected images by User", $tags="SystemDb_colors") 
System_Boundary(System_classifier, "Classifier")  {
    System_Boundary(Serving_Zone, "Serving_Zone")  {
        System(Serving_Pipeline, "Serving_Pipeline")
    }
}
Person_Ext(User, "User")

Rel(Model_Repository, Serving_Pipeline, "ML Models")
Rel(Data_Source_Production, Serving_Pipeline, "unlabelled images")
Rel(Serving_Pipeline, Log_Master, "Images with Predictions")
Rel(Serving_Pipeline, User, "proposed labelled images")
Rel(User,Serving_Pipeline, "label validation")
Rel(Serving_Pipeline, Feedback_Database, "label validation")

SHOW_FLOATING_LEGEND()

@enduml