@startuml System_classification_docs__Log_repo
!$SYSTEM_BORDER_COLOR ?= "#000000"
!include https://raw.githubUsercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(System_classifier, "Classifier")  {
    SystemDb(Log_Master, "Log_Master", $tags="SystemDb_colors") 
    SystemDb(Feedback_Database, "Feedback_Database", $tags="SystemDb_colors") 
}

SHOW_FLOATING_LEGEND()

@enduml