@startuml System_classification_docs
!$SYSTEM_BORDER_COLOR ?= "#000000"
!include https://raw.githubUsercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
HIDE_STEREOTYPE()
AddElementTag(SystemDb_colors, $bgColor=SkyBlue, $fontColor=black)

!include System_classification_docs_DevZone.puml
!include System_classification_docs_ServingZone.puml
!include System_classification_docs_MonitoringZone.puml
!include System_classification_docs_ContinuousTrainingZone.puml

SHOW_FLOATING_LEGEND()

@enduml