services:
  ocr:
    image: killiankopp/ms-ocr-ia:1.2
    container_name: ms-ocr-ia
    ports:
      - "8901:8901"
    networks:
      - sake

  etl:
    image: ms-sake-clean-text:1.1
    container_name: ms-sake-etl
    ports:
      - "8903:8903"
    networks:
      - sake
  
  preprocessing:
    image: abenayoub/ms-sake-preprocessing:1.0
    container_name: ms-sake-preprocessing
    ports:
      - "8904:8904"
    networks:
      - sake
    volumes:
      - ./data/processed/train:/app/data/processed/train
      - ./data/processed/test:/app/data/processed/test
      - ./data/vectorizers:/app/data/vectorizers
      - ./data/cleaned:/app/data/cleaned

  train:
    image: abenayoub/ms-sake-train
    container_name: ms-sake-train
    ports:
      - "8905:8905"
    networks:
      - sake
    volumes:
      - ./data/processed/train:/app/data/processed/train
      - ./data/models:/app/data/models

  gateway:
    image: docker/api-gateway
    container_name: api-gateway
    ports:
      - "8900:80"
    networks:
      - sake

networks:
  sake:
    driver: bridge