services:
  # Service OCR
  ms-OCR:
    env_file:
    - path: ./.env_mlops_sake
    image: killiankopp/ms-ocr-ia:1.1
    # le code source est dans ce repo: https://github.com/karned-kapla/ms-ocr-ia
    # l'hébergement DockerHub: https://hub.docker.com/r/killiankopp/ms-ocr-ia
    container_name: OCR
    ports:
      - ${DATA_INGESTION_PORT_OCR}:80
    networks:
      - sake

  # Service de nettoyage de texte
  ms-sake-clean-text:
    env_file:
    - path: ./.env_mlops_sake
    build:
      context: .  
      dockerfile: docker/clean_text/Dockerfile  
      args:
        SOURCE_DIR: src/data
        DOCKERFILE_DIR: docker/clean_text  
        LOG_DIR: src
      cache_from: # pour force docker-compose à regarder le cache de ce docker (quand on utilise `docker-compose up --build`)
        - ms-sake-clean-text:cache  
    image: ms-sake-clean-text:1.0 
    container_name: clean_text
    ports:
      - "8903:80"
    networks:
      - sake
    volumes: # /!\ les variables d'environnement UID et GID doivent être définies pour désigner le propriétaire hôte de ces volumes
      - ./logs:/app/logs

  # Service ETL
  ms-sake-ETL:
    env_file:
    - path: ./.env_mlops_sake
    build:
      context: .  
      dockerfile: docker/etl/Dockerfile  
      args:
        SOURCE_DIR: src/data
        DOCKERFILE_DIR: docker/etl  
        LOG_DIR: src
      cache_from: # pour force docker-compose à regarder le cache de ce docker (quand on utilise `docker-compose up --build`)
        - ms-sake-etl:cache  
    image: ms-sake-etl:1.0
    container_name: ETL
    depends_on: # pour indiquer la dépendance des dockers (Lance ces dockers /!\ ça ne vérifie pas qu'ils soient prêts)
      - ms-OCR
      - ms-sake-clean-text
    ports:
      - ${DATA_ETL_PORT_ETL}:80
    networks:
      - sake
    volumes: # /!\ les variables d'environnement UID et GID doivent être définies pour désigner le propriétaire hôte de ces volumes
      - ./data/raw_per_classes:/app/data/raw_per_classes
      - ./data/cleaned_per_classes:/app/data/cleaned_per_classes
      - ./data/ocr_raw_per_classes:/app/data/ocr_raw_per_classes
      - ./logs:/app/logs
    
  # Service de prétraitement
  ms-sake-preprocessing:
    env_file:
    - path: ./.env_mlops_sake
    build:
      context: .  
      dockerfile: docker/preprocessing/Dockerfile  
      args:
        SOURCE_DIR: src/preprocessing
        DOCKERFILE_DIR: docker/preprocessing
        LOG_DIR: src
      cache_from: # pour force docker-compose à regarder le cache de ce docker (quand on utilise `docker-compose up --build`)
        - ms-sake-preprocessing:cache
    image: ms-sake-preprocessing:1.0  
    container_name: preprocessing
    ports:
      - "8904:80"
    networks:
      - sake
    volumes: # /!\ les variables d'environnement UID et GID doivent être définies pour désigner le propriétaire hôte de ces volumes
      - ./data/cleaned_per_classes:/app/data/cleaned_per_classes
      - ./data/processed:/app/data/processed
      - ./models:/app/models
      - ./logs:/app/logs

  # Service d'entraînement
  ms-sake-train:
    env_file:
    - path: ./.env_mlops_sake
    build:
      context: .  
      dockerfile: docker/train/Dockerfile  
      args:
        SOURCE_DIR: src/train
        DOCKERFILE_DIR: docker/train
        LOG_DIR: src
      cache_from: # pour force docker-compose à regarder le cache de ce docker (quand on utilise `docker-compose up --build`)
        - ms-sake-train:cache
    image: ms-sake-train:1.0  
    container_name: train
    ports:
      - "8905:80"
    networks:
      - sake
    volumes: # /!\ les variables d'environnement UID et GID doivent être définies pour désigner le propriétaire hôte de ces volumes
      - ./data/processed/train:/app/data/processed/train
      - ./models:/app/models
      - ./logs:/app/logs

  # Service d'évaluation
  ms-sake-eval:
    env_file:
    - path: ./.env_mlops_sake
    build:
      context: .  
      dockerfile: docker/eval/Dockerfile  
      args:
        SOURCE_DIR: src/eval
        DOCKERFILE_DIR: docker/eval
        LOG_DIR: src
      cache_from: # pour force docker-compose à regarder le cache de ce docker (quand on utilise `docker-compose up --build`)
        - ms-sake-eval:cache
    image: ms-sake-eval:1.0  
    container_name: eval
    ports:
      - "8906:80"
    networks:
      - sake
    volumes: # /!\ les variables d'environnement UID et GID doivent être définies pour désigner le propriétaire hôte de ces volumes
      - ./data/processed/test:/app/data/processed/test
      - ./models:/app/models
      - ./metrics:/app/metrics
      - ./logs:/app/logs

networks:
  sake:
    driver: bridge