services:
  ocr-service:
    image: killiankopp/ms-ocr-ia:1.1
    ports:
      - "8901:80"
    networks:
      - sake

  etl-service:
    image: killiankopp/ms-sake-etl:1.0
    ports:
      - "8903:80"
    networks:
      - sake
  
  preprocessing-service:
    image: abenayoub/ms-sake-preprocessing:1.0
    ports:
      - "8904:80"
    networks:
      - sake
    volumes:
      - ./data/processed/train:/app/data/processed/train
      - ./data/processed/test:/app/data/processed/test
      - ./data/vectorizers:/app/data/vectorizers
      - ./data/cleaned:/app/data/cleaned

  train-service:
    image: abenayoub/ms-sake-train:1.0
    ports:
      - "8905:80"
    networks:
      - sake
    volumes:
      - ./data/processed/train:/app/data/processed/train
      - ./data/models:/app/data/models

networks:
  sake:
    driver: bridge