services:
  ocr:
    image: killiankopp/ms-ocr-ia:1.1
    ports:
      - "8901:8901"
    networks:
      - sake

  ms-sake-clean-text:
    build:
      context: .  
      dockerfile: docker/clean_text/Dockerfile  
      args:
        DOCKERFILE_PATH: docker/clean_text  
      cache_from:
        - ms-sake-clean-text:cache  # pour force docker-compose à regarder le cache de ce docker (/!\ à utiliser avec `docker-compose up --build`)
    image: ms-sake-clean-text:1.0  
    ports:
      - "8903:8903"
    networks:
      - sake
  
  preprocessing:
    image: abenayoub/ms-sake-preprocessing:1.0
    ports:
      - "8904:8904"
    networks:
      - sake
    volumes:
      - ./data/processed/train:/app/data/processed/train
      - ./data/processed/test:/app/data/processed/test
      - ./data/cleaned:/app/data/cleaned
      - ./models:/app/models


  train:
    image: abenayoub/ms-sake-train:1.0
    ports:
      - "8905:8905"
    networks:
      - sake
    volumes:
      - ./data/processed/train:/app/data/processed/train
      - ./models:/app/models
  
  eval:
    image: abenayoub/ms-sake-eval:1.0
    ports:
      - "8906:8906"
    networks:
      - sake
    volumes:
      - ./data/processed/test:/app/data/processed/test
      - ./models:/app/models
      - ./metrics:/app/metrics

networks:
  sake:
    driver: bridge