services:
  ocr:
    image: killiankopp/ms-ocr-ia:1.1
    ports:
      - "8901:8901"
    networks:
      - sake

  ms-sake-clean-text:
    build:
      context: .  
      dockerfile: docker/clean_text/Dockerfile  
      args:
        DOCKERFILE_PATH: docker/clean_text  
      cache_from:
        - ms-sake-clean-text:cache  # pour force docker-compose à regarder le cache de ce docker (/!\ à utiliser avec `docker-compose up --build`)
    image: ms-sake-clean-text:1.0  
    ports:
      - "8903:8903"
    networks:
      - sake

networks:
  sake:
    driver: bridge