stages:
  ingest:
    cmd:  python3 src/dvc_steps/ingest.py
    deps:
    - ${data_structure_raw.raw_dataset_dir}
    outs:
    - ${data_ingestion.ocr_text_dir}:
        persist: true

  clean:
    cmd: python3 src/dvc_steps/clean.py
    deps:
    - ${data_ingestion.ocr_text_dir}
    outs:
    - ${data_cleaning.cleaned_datasets_dir}:
        persist: true

  preprocessing:
    cmd: python3 src/dvc_steps/preprocess.py
    deps:
    - ${data_cleaning.cleaned_datasets_dir}
    outs:
    - data/processed:
        persist: true
    - models/vectorizers:
        persist: true

  train:
    cmd: python3 src/dvc_steps/train.py
    deps:
    - ${data_preprocessing.train_data_dir}
    outs:
    - ${model_train.model_train_dir}:
        persist: true

  eval:
    cmd: python3 src/dvc_steps/eval.py
    deps:
    - ${data_preprocessing.test_data_dir}
    - ${model_train.model_train_dir}
    metrics:
    - metrics/scores.json:
        cache: false
    - metrics/confusion_matrix.json:
        cache: false