stages:
  env_mlops_sake:
    cmd: python3 src/config_transform_as_env.py && python src/smart_merge_.env_.env_mlops_sake.py 
    deps:
    - params.yaml
    - src/config_transform_as_env.py
    - src/smart_merge_.env_.env_mlops_sake.py

  start_docker:
    cmd: docker-compose stop && docker-compose up --build -d && echo "Dockers démarrés" > dockers_started.txt
    deps:
    - .env_mlops_sake
    - docker-compose.yaml
    outs: []

  structure_raw:
    cmd: python3 src/data/structure_raw.py
    deps:
    - params.yaml
    - dockers_started.txt
    - data/raw
    - src/data/structure_raw.py
    - data/working_dataset.csv
    outs:
    - data/raw_per_classes:
        persist: true

  ingest:
    cmd:  'curl -X "POST" "http://localhost:8907/ingest" -H "accept: application/json"'
    #docker-compose run --rm ${data_ETL.docker_service_ETL} bash -c './scripts/ingest.sh'
    #curl -X POST ${data_ETL.endpoint_ETL_ingest_all} -H "accept: application/json"
    #'curl -X "POST" "http://${data_ETL.docker_service_ETL}:${data_ETL.port_ETL}/${data_ETL.route_ETL_ingest_all}" -H "accept: application/json"'
    deps:
    - params.yaml
    - dockers_started.txt
    - data/raw_per_classes
    outs:
    - data/ocr_raw_per_classes:
        persist: true

  clean:
    cmd: 'curl -X "POST" "http://localhost:8907/clean" -H "accept: application/json"'
    deps:
    - params.yaml
    - dockers_started.txt
    - data/ocr_raw_per_classes
    outs:
    - data/cleaned_per_classes:
        persist: true

  preprocessing:
    cmd: 'curl -X "GET" "http://localhost:8904/process"'
    deps:
    - params.yaml
    - dockers_started.txt
    - data/cleaned_per_classes
    outs:
    - data/processed:
        persist: true
    - models/vectorizers:
        persist: true

  train:
    cmd: 'curl -X "GET" "http://localhost:8905/train"'
    deps:
    - params.yaml
    - dockers_started.txt
    - data/processed/train
    outs:
    - models/train:
        persist: true

  eval:
    cmd: 'curl -X "GET" "http://localhost:8906/eval"'
    deps:
    - params.yaml
    - dockers_started.txt
    - data/processed/test
    - models/train
    metrics:
    - metrics/scores.json:
        cache: false
    - metrics/confusion_matrix.json:
        cache: false