stages:
  structure_raw:
    cmd: python3 src/data/structure_raw.py
    deps:
    - src/data/structure_raw.py
    - data/raw/final
    - data/working_dataset.csv
    outs:
    - data/raw_per_classes
  ingest:
    cmd: python3 steps/ingest.py
    deps:
    - data/raw_per_classes
    - steps/ingest.py
    outs:
    - data/ocr_raw_per_classes:
        persist: true
  clean:
    cmd: python3 steps/clean_text.py
    deps:
    - data/ocr_raw_per_classes
    - steps/clean_text.py
    outs:
    - data/cleaned