stages:
  # env_mlops_sake:
  #   cmd: 'python3 src/config_transform_as_env.py && 
  #         python src/smart_merge_.env_.env_mlops_sake.py'
  #   deps:
  #   - params.yaml
  #   - src/config_transform_as_env.py
  #   - src/smart_merge_.env_.env_mlops_sake.py

  start_dockers:
    cmd: 'source scripts/docker_clean_dangling_images.sh && 
          docker-compose stop && 
          docker-compose --profile training up --build -d && 
          date > dockers_started.txt'
    deps:
    - .env_mlops_sake
    - docker-compose.yaml
    outs:
    - dockers_started.txt

  # structure_raw:
  #   cmd: python3 src/data/structure_raw.py
  #   deps:
  #   - src/data/structure_raw.py
  #   - params.yaml
  #   - dockers_started.txt
  #   - ${data_structure_raw.image_dir}
  #   - data/working_dataset.csv
  #   outs:
  #   - ${data_structure_raw.raw_dataset_dir}:
  #       persist: true

  ingest:
    cmd:  'curl -X "POST" "http://localhost:8907/ingest"'
    deps:
    - params.yaml
    - dockers_started.txt
    - ${data_structure_raw.raw_dataset_dir}
    outs:
    - ${data_ingestion.ocr_text_dir}:
        persist: true

  clean:
    cmd: 'curl -X "POST" "http://localhost:8907/clean"'
    deps:
    - params.yaml
    - dockers_started.txt
    - ${data_ingestion.ocr_text_dir}
    outs:
    - ${data_cleaning.cleaned_datasets_dir}:
        persist: true

  preprocessing:
    cmd: 'curl -X "POST" "http://localhost:8904/process"'
    deps:
    - params.yaml
    - dockers_started.txt
    - ${data_cleaning.cleaned_datasets_dir}
    outs:
    - data/processed:
        persist: true
    - models/vectorizers:
        persist: true

  train:
    cmd: 'curl -X "POST" "http://localhost:8905/train"'
    deps:
    - params.yaml
    - dockers_started.txt
    - ${data_preprocessing.train_data_dir}
    outs:
    - ${model_train.model_train_dir}:
        persist: true

  eval:
    cmd: 'curl -X "POST" "http://localhost:8906/eval"'
    deps:
    - params.yaml
    - dockers_started.txt
    - ${data_preprocessing.test_data_dir}
    - ${model_train.model_train_dir}
    metrics:
    - metrics/scores.json:
        cache: false
    - metrics/confusion_matrix.json:
        cache: false