stages:
  ingest:
    cmd:  'curl -X "POST" "http://localhost:8907/ingest"'
    deps:
    - params.yaml
    - ${data_structure_raw.raw_dataset_dir}
    outs:
    - ${data_ingestion.ocr_text_dir}:
        persist: true

  clean:
    cmd: 'curl -X "POST" "http://localhost:8907/clean"'
    deps:
    - params.yaml
    - ${data_ingestion.ocr_text_dir}
    outs:
    - ${data_cleaning.cleaned_datasets_dir}:
        persist: true

  preprocessing:
    cmd: 'curl -X "GET" "http://localhost:8904/process"'
    deps:
    - params.yaml
    - ${data_cleaning.cleaned_datasets_dir}
    outs:
    - data/processed:
        persist: true
    - models/vectorizers:
        persist: true

  train:
    cmd: 'curl -X "GET" "http://localhost:8905/train"'
    deps:
    - params.yaml
    - ${data_preprocessing.train_data_dir}
    outs:
    - ${model_train.model_train_dir}:
        persist: true

  eval:
    cmd: 'curl -X "GET" "http://localhost:8906/eval"'
    deps:
    - params.yaml
    - ${data_preprocessing.test_data_dir}
    - ${model_train.model_train_dir}
    metrics:
    - metrics/scores.json:
        cache: false
    - metrics/confusion_matrix.json:
        cache: false