stages:
  structure_raw:
    cmd: python3 src/data/structure_raw.py
    deps:
    - src/data/structure_raw.py
    - data/raw/final
    - data/working_dataset.csv
    outs:
    - data/raw_per_classes:
        persist: true
  ingest:
    cmd: 'curl -X "POST" "http://localhost:8907/ingest" -H "accept: application/json"'
    deps:
    - data/raw_per_classes
    outs:
    - data/ocr_raw_per_classes:
        persist: true
  clean:
    cmd: 'curl -X "POST" "http://localhost:8907/clean" -H "accept: application/json"'
    deps:
    - data/ocr_raw_per_classes
    outs:
    - data/cleaned_per_classes:
        persist: true
  preprocessing:
    cmd: 'curl -X "GET" "http://localhost:8904/process"'
    deps:
    - data/cleaned_per_classes
    outs:
    - data/processed:
        persist: true
