AppName: mlflow
Namespace: sake

mlflow:
  image: ghcr.io/mlflow/mlflow:v2.17.0
  artifactRoot: "gs://sake-mlflow-storage"

gcp:
  secretName: sake-gcp-secret
  serviceAccountKey: service-account-key.json

service:
  type: ClusterIP
  port: 5000