global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'ocr-service'
    static_configs:
      - targets: ['ocr-service:80']

  - job_name: 'clean-service'
    static_configs:
      - targets: ['clean-service:80']

  - job_name: 'etl-service'
    static_configs:
      - targets: ['etl-service:80']

  - job_name: 'preprocessing-service'
    static_configs:
      - targets: ['preprocessing-service:80']

  - job_name: 'train-service'
    static_configs:
      - targets: ['train-service:80']

  - job_name: 'eval-service'
    static_configs:
      - targets: ['eval-service:80']

  - job_name: 'predict-service'
    static_configs:
      - targets: ['ms-sake-predict:80']