global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager-service 

rule_files:
  - alerting_rules.yml

scrape_configs:
  - job_name: 'ocr-service'
    static_configs:
      - targets: ['ocr-service:80']

  - job_name: 'clean-service'
    static_configs:
      - targets: ['clean-service:80']

  - job_name: 'etl-service'
    static_configs:
      - targets: ['etl-service:80']

  - job_name: 'preprocessing-service'
    static_configs:
      - targets: ['preprocessing-service:80']

  - job_name: 'train-service'
    static_configs:
      - targets: ['train-service:80']

  - job_name: 'eval-service'
    static_configs:
      - targets: ['eval-service:80']

  - job_name: 'predict-service'
    static_configs:
      - targets: ['predict-service:80']

  - job_name: 'predict-orchestrator-service'
    static_configs:
      - targets: ['predict-orchestrator-service:80']

  - job_name: 'admin-frontend-service'
    metrics_path: /_stcore/metrics
    static_configs:
      - targets: ['admin-frontend-service:80']

  - job_name: 'admin-backend-service'
    static_configs:
      - targets: ['admin-backend-service:80']

  - job_name: 'frontend-service'
    metrics_path: /_stcore/metrics
    static_configs:
      - targets: ['frontend-service:80']

  - job_name: 'orchestrator-service'
    static_configs:
      - targets: ['orchestrator-service:80']

  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:80']

  - job_name: 'node-exporter-service'
    static_configs:
      - targets: ['node-exporter-service:9100']

  - job_name: 'alertmanager-service'
    static_configs:
      - targets: ['alertmanager-service:9093']