data_structure_raw:
  raw_dataset_path: "data/working_dataset.csv" 
  image_dir: "data/raw/final/"
  raw_dataset_dir: "data/raw_per_classes/" 

data_ingestion:
  ocr_endpoint: "http://localhost:8901/txt/blocks-words"
  raw_dataset_dir: "data/raw_per_classes/"
  ocr_text_dir: "data/ocr_raw_per_classes/"
  
data_cleaning:
  clean_endpoint: "http://localhost:8903/clean"
  ocr_text_dir: "data/ocr_raw_per_classes/"
  cleaned_datasets_dir: "data/cleaned_per_classes/"

data_preprocessing:
  cleaned_datasets_dir: "data/cleaned_per_classes/"
  tfidf_vectorizer_path: "models/tfidf_vectorizer.joblib"
  train_data_dir: "data/processed/train/"
  test_data_dir: "data/processed/test/"

model_training:
  train_data_dir: "data/processed/train/"
  model_path: "models/ovrc.joblib"

model_evaluation:
  test_data_dir: "data/processed/test/"
  model_path: "models/ovrc.joblib"
  evaluation_results_dir: "metrics/"

label_encoder_mapping:
  facture: 0
  id_pieces: 1
  resume: 2