apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:{{ .Chart.AppVersion }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.PostgresDbUser }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.AppName }}-postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.PostgresDbName }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data   # Attention, ici, cela doit être /var/lib/postgresql/data (sans pgdata)
              name: postgres-storage
              subPath: pgdata   # Ce sous-répertoire sera utilisé dans le PVC
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc